<script lang="ts">
	import { enhance } from '$app/forms'; import type { ActionData, PageServerData } from './$types';
	let { data, form }: { data: PageServerData; form: ActionData } = $props();
	function moved(index: number, delta: number) { const ids = data.links.map((item) => item.id); const target = index + delta; if (target < 0 || target >= ids.length) return ids.join(','); [ids[index], ids[target]] = [ids[target], ids[index]]; return ids.join(','); }
</script>
<svelte:head><title>{data.collection.title} · LinkGarden</title><meta name="robots" content="noindex" /></svelte:head>
<p><a href="/app/lists">← All lists</a></p><h1>{data.collection.title}</h1><p>{data.isOwner ? 'You own this list.' : 'You are an editor.'} · {data.collection.visibility}{data.collection.moderationState === 'hidden' ? ' · Hidden by moderation' : ''}</p>
{#if form?.message}<p class="error" role="alert">{form.message}</p>{/if}
{#if data.isOwner}<section class="card"><h2>List settings</h2><form method="post" action="?/details" use:enhance><label>Title <input required maxlength="120" name="title" value={data.collection.title} /></label><label>Description <textarea maxlength="2000" name="description">{data.collection.description}</textarea></label><label>Visibility <select name="visibility" value={data.collection.visibility}><option value="private">Private</option><option value="public">Public</option></select></label><p>Permanent slug: {data.collection.slug}</p><button>Save list</button></form></section>{/if}
<section class="card"><h2>Add a URL</h2><form method="post" action="?/add" use:enhance><label>URL <input required type="url" name="url" /></label><label>Title (optional) <input maxlength="300" name="title" /></label><label>Description <textarea maxlength="2000" name="description"></textarea></label><label>Tags <input name="tags" /></label><button>Add to list</button></form>
{#if data.personalLinks.length}<form method="post" action="?/copy" use:enhance><label>Or copy one of your personal links <select name="personalLinkId">{#each data.personalLinks as item}<option value={item.id}>{item.title}</option>{/each}</select></label><button class="secondary">Copy into list</button></form>{/if}</section>
<section class="stack"><h2>Ordered links</h2>{#each data.links as item, index}<article class="card"><form method="post" action="?/editLink" use:enhance><input type="hidden" name="linkId" value={item.id} /><label>Title <input required maxlength="300" name="title" value={item.title} /></label><label>Description <textarea maxlength="2000" name="description">{item.description}</textarea></label><label>Tags <input name="tags" value={item.tags.join(', ')} /></label><p><a href={item.normalizedUrl} rel="noreferrer">{item.normalizedUrl}</a> · {item.metadataStatus}</p><button>Save link</button></form><div class="actions">{#if index > 0}<form method="post" action="?/reorder" use:enhance><input type="hidden" name="orderedIds" value={moved(index, -1)} /><button class="secondary" aria-label={'Move ' + item.title + ' up'}>↑</button></form>{/if}{#if index < data.links.length - 1}<form method="post" action="?/reorder" use:enhance><input type="hidden" name="orderedIds" value={moved(index, 1)} /><button class="secondary" aria-label={'Move ' + item.title + ' down'}>↓</button></form>{/if}<form method="post" action="?/removeLink" use:enhance><input type="hidden" name="linkId" value={item.id} /><button class="danger">Remove</button></form></div></article>{:else}<p>No links in this list.</p>{/each}</section>
<section class="card"><h2>Editors</h2><ul>{#each data.members as member}<li>{member.displayName} (@{member.username}) {#if data.isOwner}<span class="actions"><form method="post" action="?/removeEditor" use:enhance><input type="hidden" name="userId" value={member.userId} /><button class="secondary">Remove</button></form><form method="post" action="?/transfer" use:enhance><input type="hidden" name="userId" value={member.userId} /><button>Transfer ownership</button></form></span>{/if}</li>{:else}<li>No editors.</li>{/each}</ul>
{#if data.isOwner}<form method="post" action="?/invite" use:enhance><label>Invite by username or email <input required name="recipient" /></label><button>Invite editor</button></form>{#each data.invitations as invitation}<div>Pending: {invitation.recipientEmail ?? invitation.recipientUserId}<form class="inline" method="post" action="?/revoke" use:enhance><input type="hidden" name="invitationId" value={invitation.id} /><button class="secondary">Revoke</button></form></div>{/each}{:else}<form method="post" action="?/leave"><button class="danger">Leave list</button></form>{/if}</section>
{#if data.isOwner}<section class="card danger-zone"><h2>Delete list</h2><p>This permanently deletes this list and its independent list links.</p><form method="post" action="?/deleteList"><button class="danger">Delete list</button></form></section>{/if}
